	mpiexec -n 1 python sample_EDM_diffusion_real.py \
	--attention_resolutions 32,16,8 \
	--steps 40 \
	--image_size 256 \
	--learn_sigma True \
	--noise_schedule karas \
	--num_channels 128 \
	--num_head_channels 64 \
	--num_res_blocks 2 \
	--resblock_updow True \
	--use_scale_shift_norm True \
	--burst_size 8 \
	--num_cond_features 48 \
	--batch_size 1 \
	--timestep_respacing 10  \
	--model_path /consistency_models/logs/edm_scratch_2024-12-21_14-33s_max80.0_burst8_synthetic/model030000.pt \
	--gpu_id 1 \
	--input_path /BurstSR/real \
	--crop_size 32 \
	--save_png True \
	--start_step_list "5" \
	--pre_model_list "BIPNet,Burstormer" \
	--ts '' \
	--sampler heun_bsr \
	--s_tmax 100 \
	--trial False \
	--seed 38 \
	--sigma_max 0.03 \
	--sigma_min 0.00000001 \
	--task bsr
# CUDA_VISIBLE_DEVICES=6 sh sample_EDM_real.sh